### PR TITLE
fix: increased default expires time to AWS pre-signed url operations

### PR DESCRIPTION
**Pull request by LpmRaven**
I believe we should increase the default expires time to match AWS. 

```
Expires (Integer) — default: 900 — the number of seconds to expire the pre-signed URL operation in. Defaults to 15 minutes.
```
from [AWS getSignedUrl Docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)

This new feature broke my websites as it was a change to the interface (with a default) - should have probably been a major version. A great feature to add though, Thanks @Vacilando .

### CODE REVIEW

**Comment by robinmetral** [comment]
@LpmRaven thank you for this 🙏  We thought that the default was 60 seconds, not 900. Very sorry about the unintended breaking change! Let's make this a fix and I'll deprecate version 2.1.0 in NPM.

**Comment by robinmetral** [comment]
The only weird thing here is that GitHub Actions didn't seem to pick up the PR. Could you try changing the commit hash and pushing again, @LpmRaven? I'll merge when the CI is green, for sanity's sake 🙂

**Comment by LpmRaven** [comment]
> The only weird thing here is that GitHub Actions didn't seem to pick up the PR. Could you try changing the commit hash and pushing again, @LpmRaven? I'll merge when the CI is green, for sanity's sake 🙂

Yeah sure, just pushed with a corrected commit name, let me know if it's still not triggering.

**Comment by robinmetral** [comment]
Ah, right, sorry! I was confused because it runs for renovate branches, but that's because they're not forks. I'll fix this asap. Thanks for bearing with me 🙏

**Comment by LpmRaven** [comment]
I made a mess of this - will make a new PR.

**Pull request closed without merging**
